verify:
  model_name: ep-20250102085733-6dx7v
  prompt_path: /root/autodl-tmp/xiao/CFG_generate/pipelines/prompts/rationality_verfication.txt 
  api_key: 88ea5643-8049-4f60-abb3-772a2420cf6d
  url: https://ark.cn-beijing.volces.com/api/v3

transform:
  model_name: ep-20250102085733-6dx7v
  prompt_path: /root/autodl-tmp/xiao/CFG_generate/pipelines/prompts/transform.txt 
  api_key: 88ea5643-8049-4f60-abb3-772a2420cf6d
  url: https://ark.cn-beijing.volces.com/api/v3
  cot_sample_path: /root/autodl-tmp/xiao/CFG_generate/tmp/stage3_cot_sample.json

fill_regex:
  model_name: ep-20250102085733-6dx7v
  prompt_path: /root/autodl-tmp/xiao/CFG_generate/pipelines/prompts/fill_regex.txt 
  api_key: 88ea5643-8049-4f60-abb3-772a2420cf6d
  url: https://ark.cn-beijing.volces.com/api/v3
  cot_sample_path: /root/autodl-tmp/xiao/CFG_generate/tmp/stage3_cot_sample.json
  train_prompt: false
  train_dataset_path: demo.json

io_related:
  grammar_path: /root/autodl-tmp/xiao/CFG_generate/grammars/querylang.g4
  grammar_help_path: /root/autodl-tmp/xiao/CFG_generate/grammars/grammar_help.txt
  stage1_output_path: /root/autodl-tmp/xiao/CFG_generate/tmp/stage1_output.txt 
  stage2_output_path: /root/autodl-tmp/xiao/CFG_generate/tmp/stage2_output.txt

regex_related:
  re_lexical_rules_special_token: ["<|lexical_re_start|>", "<|lexical_re_end|>"]

control:
  transform_epochs: 3
  fill_regex_max_retries: 3
  num_jobs: 8
