
#process
grammar_path: grammars_samples/querylang.g4 #only support antlr now
start_rule: query
re_lexical_rules: ["STRING_CONTENT", "NUMBER_VALUE"]
re_lexical_rules_special_token: ["<re>", "</re>"]

#generate
num_samples: 10000
output_dir: tmp/stage1_output.txt
max_depth: 100
random_seed: 42
jobs: 8
max_tokens: 200

#parser
parser_dir: src/parse/grammars
