dsl2nl_server:
  model_name: ep-20250102085733-6dx7v
  prompt_path: pipelines/prompts/stage3_dsl2nl.txt 
  api_key: 88ea5643-8049-4f60-abb3-772a2420cf6d
  url: https://ark.cn-beijing.volces.com/api/v3
  cot_sample_path:
  train_prompt: false
  train_dataset_path: demo.json
  train_metric: rouge  # now only support rouge
  train_metric_threshold: 0.5
  
verify:
  model_name: ep-20250102085733-6dx7v
  prompt_path: pipelines/prompts/stage3_vertify.txt 
  api_key: 88ea5643-8049-4f60-abb3-772a2420cf6d
  url: https://ark.cn-beijing.volces.com/api/v3

transform:
  model_name: ep-20250102085733-6dx7v
  prompt_path: pipelines/prompts/stage3_transform.txt 
  api_key: 88ea5643-8049-4f60-abb3-772a2420cf6d
  url: https://ark.cn-beijing.volces.com/api/v3

io_related:
  grammar_path: grammars_samples/querylang.g4
  grammar_help_path: grammars_samples/grammar_help.txt
  stage2_output_path: tmp/stage2_output.txt
  stage3_output_path: tmp/stage3_output.json
  roles_path: pipelines/roles/persona.json

control:
  dsl2nl_epochs: 3
  transform_epochs: 3
  num_jobs: 8