verify:
  model_name: qwen_72b_awq
  prompt_path: pipelines/prompts/stage2_vertify.txt
  api_key: uos_xiao
  url: https://u468127-bfba-8e9ec43e.westx.seetacloud.com:8443/v1

transform:
  model_name: qwen_72b_awq
  prompt_path: pipelines/prompts/stage2_transform.txt 
  api_key: uos_xiao
  url: https://u468127-bfba-8e9ec43e.westx.seetacloud.com:8443/v1

fill_regex:
  model_name: qwen_72b_awq
  prompt_path: pipelines/prompts/stage2_fill_regex.txt
  api_key: uos_xiao
  url: https://u468127-bfba-8e9ec43e.westx.seetacloud.com:8443/v1
  cot_sample_path: 
  train_prompt: false
  train_dataset_path: demo.json
  train_metric: rouge
  train_metric_threshold: 0.5
  parser_dir: src/parse/grammars

io_related:
  grammar_path: grammars_samples/querylang.g4
  grammar_help_path: grammars_samples/grammar_help.txt
  stage1_output_path: tmp/stage1_output.txt 
  stage2_output_path: tmp/stage2_output.txt

regex_related:
  re_lexical_rules_special_token: ["<re>", "</re>"]
control:
  transform_epochs: 3
  fill_regex_max_retries: 3
  num_jobs: 8
