
#process
grammar_path: grammars/querylang.g4 #only support antlr now
start_rule: query
re_lexical_rules: ["STRING_VALUE", "NUMBER_VALUE"]
re_lexical_rules_special_token: ["<|lexical_re_start|>", "<|lexical_re_end|>"]

#generate
num_samples: 10000
output_dir: tmp/stage1_output1.txt
max_depth: 100
random_seed: 
jobs: 1
max_tokens: 200

