dsl2nl_server:
  model_name: deepseek/deepseek-r1/community
  prompt_path: pipelines/prompts/stage3_dsl2nl.txt 
  api_key: sk_1vNkoXwW5Uv9zqlWzhIk5Cc8VI8VRQbYKjFVwro8row
  url: https://api.ppinfra.com/v3/openai
  cot_sample_path:
  train_prompt: false
  train_dataset_path: demo.json
  train_metric: rouge  # now only support rouge
  train_metric_threshold: 0.5
  
verify:
  model_name: deepseek/deepseek-r1/community
  prompt_path: pipelines/prompts/stage3_vertify.txt 
  api_key: sk_1vNkoXwW5Uv9zqlWzhIk5Cc8VI8VRQbYKjFVwro8row
  url: https://api.ppinfra.com/v3/openai

transform:
  model_name: deepseek/deepseek-r1/community
  prompt_path: pipelines/prompts/stage3_transform.txt 
  api_key: sk_1vNkoXwW5Uv9zqlWzhIk5Cc8VI8VRQbYKjFVwro8row
  url: https://api.ppinfra.com/v3/openai

io_related:
  grammar_path: grammars_samples/querylang.g4
  grammar_help_path: grammars_samples/grammar_help.txt
  stage2_output_path: tmp_tmp_deepseek-r1/stage2_output.txt
  stage3_output_path: tmp_tmp_deepseek-r1/stage3_output.json
  roles_path: pipelines/roles/persona.json

control:
  dsl2nl_epochs: 3
  transform_epochs: 3
  num_jobs: 4